In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('../data/master_campus_demand_W1_to_W16.csv')
df.head()

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
0,1,Monday,0,Grainger Library,0.0,1.0,0
1,1,Monday,0,Funk Library,0.0,1.0,0
2,1,Monday,0,Main Library,-1.0,1.0,0
3,1,Monday,0,Illini Union,-1.0,1.0,0
4,1,Monday,0,CIF,-1.0,1.0,0

In [8]:
# Monday, 7 pm 
df[(df['Week'] == 3) & (df['Day'] == 'Monday') & (df['Hour'] == 19)]

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
2840,3,Monday,19,Grainger Library,0.401,1.133,355
2841,3,Monday,19,Funk Library,0.115,1.133,355
2842,3,Monday,19,Main Library,0.286,1.133,355
2843,3,Monday,19,Illini Union,0.696,1.133,355
2844,3,Monday,19,CIF,0.354,1.133,355
2845,3,Monday,19,BIF,0.229,1.133,355
2846,3,Monday,19,Siebel Center for CS,0.229,1.133,355
2847,3,Monday,19,Siebel Center for Design,0.073,1.133,355

In [10]:
# [Week], [Day], [Time]
df[(df['Week'] == 8) & (df['Day'] == 'Saturday') & (df['Hour'] == 14)]

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
10480,8,Saturday,14,Grainger Library,0.392,1.0,1310
10481,8,Saturday,14,Funk Library,0.300,1.0,1310
10482,8,Saturday,14,Main Library,0.210,1.0,1310
10483,8,Saturday,14,Illini Union,0.273,1.0,1310
10484,8,Saturday,14,CIF,0.346,1.0,1310
10485,8,Saturday,14,BIF,0.168,1.0,1310
10486,8,Saturday,14,Siebel Center for CS,0.224,1.0,1310
10487,8,Saturday,14,Siebel Center for Design,0.191,1.0,1310

## Calendar

In [ ]:
# [Week], [Day], [Time]
df[(df['Week'] == 12) & (df['Day'] == 'Wednesday') & (df['Hour'] == 11)]

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
14872,12,Monday,11,Grainger Library,0.505,1.428,1859
14873,12,Monday,11,Funk Library,0.858,1.428,1859
14874,12,Monday,11,Main Library,0.692,1.428,1859
14875,12,Monday,11,Illini Union,0.945,1.428,1859
14876,12,Monday,11,CIF,0.446,1.428,1859
14877,12,Monday,11,BIF,0.554,1.428,1859
14878,12,Monday,11,Siebel Center for CS,0.289,1.428,1859
14879,12,Monday,11,Siebel Center for Design,0.546,1.428,1859

In [13]:
# [Week], [Day], [Time]
df[(df['Week'] == 16) & (df['Day'] == 'Tuesday') & (df['Hour'] == 15)]

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
20472,16,Tuesday,15,Grainger Library,1.000,1.6,2559
20473,16,Tuesday,15,Funk Library,1.000,1.6,2559
20474,16,Tuesday,15,Main Library,1.000,1.6,2559
20475,16,Tuesday,15,Illini Union,0.645,1.6,2559
20476,16,Tuesday,15,CIF,0.975,1.6,2559
20477,16,Tuesday,15,BIF,0.868,1.6,2559
20478,16,Tuesday,15,Siebel Center for CS,0.629,1.6,2559
20479,16,Tuesday,15,Siebel Center for Design,0.729,1.6,2559