In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/master_campus_demand_W1_to_W16.csv')
df.head()

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
0,1,Monday,0,Grainger Library,0.0,1.0,0
1,1,Monday,0,Funk Library,0.0,1.0,0
2,1,Monday,0,Main Library,0.0,1.0,0
3,1,Monday,0,Illini Union,0.0,1.0,0
4,1,Monday,0,CIF,0.0,1.0,0

In [3]:
# Monday, 7 pm 
df[(df['Week'] == 3) & (df['Day'] == 'Monday') & (df['Hour'] == 19)]

,Week,Day,Hour,Building,Demand_Prediction,Pressure_Multiplier,Timestep
2840,3,Monday,19,Grainger Library,0.401,1.133,355
2841,3,Monday,19,Funk Library,0.115,1.133,355
2842,3,Monday,19,Main Library,0.286,1.133,355
2843,3,Monday,19,Illini Union,0.696,1.133,355
2844,3,Monday,19,CIF,0.374,1.133,355
2845,3,Monday,19,BIF,0.200,1.133,355
2846,3,Monday,19,Siebel Center for CS,0.187,1.133,355
2847,3,Monday,19,Siebel Center for Design,0.080,1.133,355

In [ ]:
# [Week], [Day], [Time]
df[(df['Week'] == 3) & (df['Day'] == 'Monday') & (df['Hour'] == 19)]