In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/fa2024.csv')
df.head()

,CRN,Course Subject,Course Number,Course Title,Course Section,Sched Type,Term,Primary Instructor,A Range,B Range,...,B-,C+,C,C-,D+,D,D-,F,W,Average Grade
0,41758,AAS,100,Intro Asian American Studies,AD1,DIS,120248,"Wang, Yu",NaN,NaN,...,0,1,1,0,0,0,0,0,0,3.77
1,47100,AAS,100,Intro Asian American Studies,AD2,DIS,120248,"Wang, Yu",NaN,NaN,...,1,0,1,0,0,1,0,0,0,3.67
2,51249,AAS,100,Intro Asian American Studies,AD5,DIS,120248,"Kim, Gabriel D",NaN,NaN,...,0,0,0,1,0,0,0,0,0,3.61
3,51932,AAS,100,Intro Asian American Studies,AD6,DIS,120248,"Kim, Gabriel D",NaN,NaN,...,1,0,0,0,0,0,0,1,0,3.69
4,59820,AAS,100,Intro Asian American Studies,AD9,DIS,120248,"Mukhopadhyay, Anirban",NaN,NaN,...,0,1,0,0,1,0,0,0,0,3.73

In [3]:
df = df.drop(columns=['Term', 'A Range', 'B Range', 'C Range', 'D Range'])
df.head()

,CRN,Course Subject,Course Number,Course Title,Course Section,Sched Type,Primary Instructor,A+,A,A-,...,B-,C+,C,C-,D+,D,D-,F,W,Average Grade
0,41758,AAS,100,Intro Asian American Studies,AD1,DIS,"Wang, Yu",16,5,3,...,0,1,1,0,0,0,0,0,0,3.77
1,47100,AAS,100,Intro Asian American Studies,AD2,DIS,"Wang, Yu",14,5,2,...,1,0,1,0,0,1,0,0,0,3.67
2,51249,AAS,100,Intro Asian American Studies,AD5,DIS,"Kim, Gabriel D",9,5,2,...,0,0,0,1,0,0,0,0,0,3.61
3,51932,AAS,100,Intro Asian American Studies,AD6,DIS,"Kim, Gabriel D",14,6,1,...,1,0,0,0,0,0,0,1,0,3.69
4,59820,AAS,100,Intro Asian American Studies,AD9,DIS,"Mukhopadhyay, Anirban",15,4,2,...,0,1,0,0,1,0,0,0,0,3.73

In [4]:
num_cols = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F', 'Students']
agg_dict = {col: 'sum' for col in num_cols}
agg_dict.update({
    'Course Subject': 'first',
    'Course Number': 'first'
})

df['Students'] = df['A+'] + df['A'] + df['A-'] + df['B+'] + df['B'] + df['B-'] + df['C+'] + df['C'] + df['C-'] + df['D+'] + df['D'] + df['D-'] + df['F']
df['Course'] = df['Course Subject'] + ' ' + df['Course Number'].astype(str)
df_grouped = df.groupby('Course').agg(agg_dict).reset_index()
df_grouped.head()

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number
0,AAS 100,87,30,12,5,11,2,2,2,1,1,1,0,1,155,AAS,100
1,AAS 120,0,16,1,2,1,0,0,1,0,0,0,0,0,21,AAS,120
2,AAS 200,2,15,4,1,3,2,0,1,1,0,0,0,1,30,AAS,200
3,AAS 246,6,21,2,0,0,0,0,0,1,0,0,0,0,30,AAS,246
4,ABE 127,2,44,4,1,0,0,0,0,0,0,0,0,0,51,ABE,127

In [5]:
df_grouped['Average Grade'] = (4.0 * df_grouped['A+'] + 4.0 * df_grouped['A'] + 3.7 * df_grouped['A-'] + 3.3 * df_grouped['B+'] + 3.0 * df_grouped['B'] + 2.7 * df_grouped['B-'] + 2.3 * df_grouped['C+'] + 2.0 * df_grouped['C'] + 1.7 * df_grouped['C-'] + 1.3 * df_grouped['D+'] + 1.0 * df_grouped['D'] + 0.7 * df_grouped['D-'] + 0.0 * df_grouped['F']) / df_grouped['Students']
df_grouped.head()

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
0,AAS 100,87,30,12,5,11,2,2,2,1,1,1,0,1,155,AAS,100,3.741290
1,AAS 120,0,16,1,2,1,0,0,1,0,0,0,0,0,21,AAS,120,3.776190
2,AAS 200,2,15,4,1,3,2,0,1,1,0,0,0,1,30,AAS,200,3.473333
3,AAS 246,6,21,2,0,0,0,0,0,1,0,0,0,0,30,AAS,246,3.903333
4,ABE 127,2,44,4,1,0,0,0,0,0,0,0,0,0,51,ABE,127,3.962745

In [6]:
df_grouped[(df_grouped['Average Grade'] < 3.3) & (df_grouped['Students'] >= 600)]

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
362,CHEM 101,26,131,112,127,155,117,100,65,39,33,30,19,64,1018,CHEM,101,2.706189
363,CHEM 102,79,229,199,240,297,173,234,218,151,71,63,27,31,2012,CHEM,102,2.745278
365,CHEM 104,40,62,51,57,99,106,83,106,114,31,18,21,23,811,CHEM,104,2.512577
373,CHEM 232,64,140,79,69,55,55,41,52,29,32,15,12,31,674,CHEM,232,2.911128
455,CS 173,0,226,81,66,72,42,33,27,15,8,11,9,14,604,CS,173,3.201987
527,ECE 110,88,187,79,53,63,40,31,24,12,14,13,0,13,617,ECE,110,3.298379
906,IB 150,31,150,92,79,71,55,35,42,20,16,6,7,10,614,IB,150,3.121824
1113,MATH 220,86,139,78,62,79,49,44,61,32,26,27,17,105,805,MATH,220,2.624596
1114,MATH 221,55,121,120,108,110,60,40,39,25,8,26,9,22,743,MATH,221,3.030417
1116,MATH 231,195,226,138,143,118,69,76,64,61,5,33,2,21,1151,MATH,231,3.174805
1117,MATH 241,118,308,287,214,256,195,101,143,110,71,73,35,128,2039,MATH,241,2.776704
1118,MATH 257,121,183,87,82,93,62,48,53,26,25,27,0,5,812,MATH,257,3.171182
1300,PHYS 211,194,176,78,55,40,57,40,38,31,19,15,24,12,779,PHYS,211,3.210783
1301,PHYS 212,136,82,66,40,55,54,41,56,34,13,8,20,7,612,PHYS,212,3.042484

In [7]:
df_grouped[(df_grouped['Course Subject'] == 'ACCY') & (df_grouped['Course Number'] < 400)]

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
9,ACCY 200,186,147,64,40,26,8,9,3,2,1,2,0,1,489,ACCY,200,3.750102
10,ACCY 201,122,98,61,40,41,25,21,35,19,5,8,6,3,484,ACCY,201,3.300620
11,ACCY 202,47,75,28,32,46,15,12,12,6,0,8,0,0,281,ACCY,202,3.364769
12,ACCY 301,41,32,26,31,26,16,7,8,9,1,3,0,2,202,ACCY,301,3.284158
13,ACCY 302,13,52,31,44,13,12,15,2,3,1,0,0,1,187,ACCY,302,3.402139
14,ACCY 303,20,77,16,19,23,22,10,8,3,2,1,2,3,206,ACCY,303,3.336893
15,ACCY 304,14,52,24,28,47,13,6,7,2,0,0,0,3,196,ACCY,304,3.329082
16,ACCY 312,18,29,36,35,24,23,2,12,0,1,0,0,0,180,ACCY,312,3.337222

In [8]:
df_grouped[(df_grouped['Course Subject'] == 'FIN') & (df_grouped['Course Number'] < 500)].sort_values('Students', ascending=False)

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
700,FIN 221,21,505,151,92,65,27,14,16,3,2,4,0,2,902,FIN,221,3.669734
704,FIN 321,19,88,46,26,34,4,0,2,0,0,1,0,0,220,FIN,321,3.644545
701,FIN 230,7,154,38,7,5,1,0,0,1,0,0,0,0,213,FIN,230,3.883099
703,FIN 300,12,39,32,21,27,11,12,13,10,3,2,1,2,185,FIN,300,3.132973
702,FIN 241,9,139,11,10,10,3,0,0,0,0,0,0,0,182,FIN,241,3.867033
714,FIN 435,0,117,18,2,6,0,0,1,0,0,0,1,1,146,FIN,435,3.848630
707,FIN 411,23,32,37,17,4,4,0,0,1,0,2,0,1,121,FIN,411,3.632231
710,FIN 423,42,68,2,0,2,0,0,0,0,0,0,0,0,114,FIN,423,3.977193
705,FIN 392,1,57,0,0,4,0,0,0,0,0,0,0,0,62,FIN,392,3.935484
708,FIN 412,1,23,17,11,6,3,0,0,0,0,0,0,0,61,FIN,412,3.627869
706,FIN 393,0,54,3,0,1,1,0,0,0,0,0,0,0,59,FIN,393,3.945763
717,FIN 463,0,33,4,8,4,5,3,1,1,0,0,0,0,59,FIN,463,3.547458
709,FIN 418,14,12,13,4,4,0,1,2,0,0,1,0,0,51,FIN,418,3.619608
715,FIN 445,15,19,5,6,2,1,1,0,1,0,0,0,0,50,FIN,445,3.740000
716,FIN 447,25,11,9,2,0,1,0,0,1,0,0,0,0,49,FIN,447,3.842857
718,FIN 464,11,22,3,3,1,1,0,0,0,0,0,0,0,41,FIN,464,3.870732
713,FIN 433,0,11,7,4,2,2,2,3,1,0,0,0,0,32,FIN,433,3.337500
711,FIN 424,5,10,4,3,2,2,1,0,1,1,1,0,0,30,FIN,424,3.413333
712,FIN 432,4,11,2,0,4,1,0,0,1,0,0,0,0,23,FIN,432,3.643478