In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/sp2025.csv')
df.head()

,CRN,Course Subject,Course Number,Course Title,Course Section,Sched Type,Term,Primary Instructor,A Range,B Range,...,B-,C+,C,C-,D+,D,D-,F,W,Average Grade
0,69781,AAS,100,Intro Asian American Studies,AB,LCD,120251,"Geng, Zhe",NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.75
1,30107,AAS,100,Intro Asian American Studies,AD1,DIS,120251,"Wang, Yu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41729,AAS,100,Intro Asian American Studies,AD2,DIS,120251,"Wang, Yu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43832,AAS,100,Intro Asian American Studies,AD3,DIS,120251,"Kim, Gabriel D",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,48232,AAS,100,Intro Asian American Studies,AD4,DIS,120251,"Kim, Gabriel D",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = df.drop(columns=['Term', 'A Range', 'B Range', 'C Range', 'D Range'])
df.head()

,CRN,Course Subject,Course Number,Course Title,Course Section,Sched Type,Primary Instructor,A+,A,A-,...,B-,C+,C,C-,D+,D,D-,F,W,Average Grade
0,69781,AAS,100,Intro Asian American Studies,AB,LCD,"Geng, Zhe",3.0,21.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.75
1,30107,AAS,100,Intro Asian American Studies,AD1,DIS,"Wang, Yu",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41729,AAS,100,Intro Asian American Studies,AD2,DIS,"Wang, Yu",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43832,AAS,100,Intro Asian American Studies,AD3,DIS,"Kim, Gabriel D",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,48232,AAS,100,Intro Asian American Studies,AD4,DIS,"Kim, Gabriel D",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
num_cols = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F', 'Students']
agg_dict = {col: 'sum' for col in num_cols}
agg_dict.update({
    'Course Subject': 'first',
    'Course Number': 'first'
})

df['Students'] = df['A+'] + df['A'] + df['A-'] + df['B+'] + df['B'] + df['B-'] + df['C+'] + df['C'] + df['C-'] + df['D+'] + df['D'] + df['D-'] + df['F']
df['Course'] = df['Course Subject'] + ' ' + df['Course Number'].astype(str)
df_grouped = df.groupby('Course').agg(agg_dict).reset_index()
df_grouped.head()

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number
0,AAS 100,3.0,21.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,28.0,AAS,100
1,AAS 200,0.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.0,AAS,200
2,AAS 211,0.0,22.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,AAS,211
3,AAS 215,5.0,12.0,5.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,30.0,AAS,215
4,AAS 287,9.0,12.0,8.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,31.0,AAS,287

In [5]:
df_grouped['Average Grade'] = (4.0 * df_grouped['A+'] + 4.0 * df_grouped['A'] + 3.7 * df_grouped['A-'] + 3.3 * df_grouped['B+'] + 3.0 * df_grouped['B'] + 2.7 * df_grouped['B-'] + 2.3 * df_grouped['C+'] + 2.0 * df_grouped['C'] + 1.7 * df_grouped['C-'] + 1.3 * df_grouped['D+'] + 1.0 * df_grouped['D'] + 0.7 * df_grouped['D-'] + 0.0 * df_grouped['F']) / df_grouped['Students']
df_grouped.head()

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
0,AAS 100,3.0,21.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,28.0,AAS,100,3.750000
1,AAS 200,0.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,34.0,AAS,200,3.882353
2,AAS 211,0.0,22.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,AAS,211,3.958333
3,AAS 215,5.0,12.0,5.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,30.0,AAS,215,3.656667
4,AAS 287,9.0,12.0,8.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,31.0,AAS,287,3.816129

In [6]:
df_grouped[(df_grouped['Average Grade'] < 3.3) & (df_grouped['Students'] >= 600)]

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
661,CHEM 102,36.0,93.0,77.0,115.0,176.0,131.0,169.0,178.0,83.0,54.0,46.0,20.0,18.0,1196.0,CHEM,102,2.573662
663,CHEM 104,82.0,164.0,132.0,111.0,154.0,123.0,64.0,117.0,136.0,34.0,52.0,39.0,12.0,1220.0,CHEM,104,2.761230
820,CS 173,0.0,248.0,132.0,92.0,97.0,62.0,38.0,34.0,13.0,21.0,12.0,13.0,12.0,774.0,CS,173,3.189018
833,CS 374,50.0,109.0,70.0,94.0,76.0,94.0,53.0,44.0,23.0,12.0,8.0,8.0,6.0,647.0,CS,374,3.037403
2050,MATH 220,25.0,73.0,57.0,47.0,53.0,52.0,54.0,36.0,23.0,26.0,42.0,19.0,104.0,611.0,MATH,220,2.261538
2053,MATH 231,145.0,201.0,74.0,211.0,123.0,57.0,82.0,56.0,45.0,5.0,21.0,7.0,18.0,1045.0,MATH,231,3.144976
2055,MATH 241,86.0,238.0,153.0,113.0,167.0,59.0,57.0,82.0,33.0,21.0,22.0,9.0,22.0,1062.0,MATH,241,3.109322
2056,MATH 257,96.0,511.0,250.0,191.0,201.0,116.0,80.0,81.0,53.0,44.0,40.0,0.0,27.0,1690.0,MATH,257,3.214675
2108,MCB 150,94.0,114.0,78.0,76.0,71.0,81.0,51.0,29.0,20.0,6.0,6.0,0.0,1.0,627.0,MCB,150,3.231579
2521,PHYS 211,251.0,219.0,119.0,115.0,92.0,112.0,94.0,89.0,56.0,36.0,22.0,22.0,8.0,1235.0,PHYS,211,3.118866

In [7]:
df_grouped[df_grouped['Course'] == 'CHEM 232']

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
669,CHEM 232,33.0,71.0,59.0,53.0,88.0,56.0,46.0,45.0,37.0,22.0,22.0,17.0,34.0,583.0,CHEM,232,2.651115

In [8]:
df_grouped[(df_grouped['Course Subject'] == 'ACCY') & (df_grouped['Course Number'] < 400)]

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
22,ACCY 200,240.0,161.0,55.0,27.0,25.0,12.0,3.0,1.0,3.0,0.0,0.0,1.0,3.0,531.0,ACCY,200,3.801695
23,ACCY 201,151.0,88.0,37.0,22.0,18.0,11.0,18.0,24.0,11.0,4.0,10.0,0.0,0.0,394.0,ACCY,201,3.483503
24,ACCY 202,66.0,90.0,49.0,46.0,60.0,25.0,20.0,26.0,7.0,0.0,5.0,0.0,0.0,394.0,ACCY,202,3.348985
25,ACCY 301,35.0,30.0,18.0,25.0,19.0,7.0,12.0,3.0,3.0,1.0,2.0,3.0,1.0,159.0,ACCY,301,3.327673
26,ACCY 302,32.0,40.0,23.0,24.0,16.0,2.0,4.0,1.0,2.0,1.0,1.0,1.0,0.0,147.0,ACCY,302,3.559864
27,ACCY 303,15.0,63.0,9.0,17.0,11.0,4.0,8.0,9.0,3.0,5.0,0.0,1.0,2.0,147.0,ACCY,303,3.359864
28,ACCY 304,20.0,39.0,10.0,22.0,56.0,11.0,5.0,3.0,0.0,1.0,1.0,1.0,1.0,170.0,ACCY,304,3.316471
29,ACCY 312,12.0,33.0,21.0,33.0,26.0,8.0,1.0,6.0,0.0,0.0,1.0,1.0,1.0,143.0,ACCY,312,3.372028
30,ACCY 375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ACCY,375,NaN
31,ACCY 398,0.0,119.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,1.0,128.0,ACCY,398,3.835938

In [9]:
df_grouped[(df_grouped['Course Subject'] == 'BADM') & (df_grouped['Course Number'] < 500)].sort_values('Students', ascending=False)

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
468,BADM 310,468.0,214.0,69.0,35.0,29.0,12.0,8.0,4.0,2.0,0.0,0.0,0.0,3.0,844.0,BADM,310,3.848341
473,BADM 320,196.0,287.0,39.0,53.0,45.0,7.0,17.0,9.0,3.0,0.0,3.0,0.0,2.0,661.0,BADM,320,3.737216
511,BADM 449,17.0,238.0,75.0,42.0,37.0,12.0,8.0,3.0,0.0,0.0,1.0,0.0,0.0,433.0,BADM,449,3.706467
466,BADM 275,49.0,223.0,65.0,32.0,12.0,3.0,4.0,3.0,1.0,1.0,0.0,0.0,0.0,393.0,BADM,275,3.807634
465,BADM 211,98.0,112.0,55.0,34.0,22.0,10.0,5.0,5.0,0.0,0.0,0.0,1.0,0.0,342.0,BADM,211,3.716082
467,BADM 300,111.0,63.0,32.0,21.0,23.0,13.0,1.0,7.0,0.0,1.0,1.0,0.0,1.0,274.0,BADM,300,3.672993
464,BADM 210,21.0,176.0,8.0,11.0,10.0,9.0,3.0,4.0,1.0,1.0,0.0,0.0,1.0,245.0,BADM,210,3.780000
469,BADM 311,10.0,26.0,42.0,30.0,11.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,123.0,BADM,311,3.560976
485,BADM 340,56.0,39.0,9.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,116.0,BADM,340,3.760345
489,BADM 351,0.0,99.0,8.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,112.0,BADM,351,3.922321
488,BADM 350,1.0,74.0,19.0,9.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,106.0,BADM,350,3.846226
472,BADM 314,0.0,23.0,20.0,20.0,12.0,8.0,2.0,0.0,1.0,2.0,0.0,0.0,4.0,92.0,BADM,314,3.244565
470,BADM 312,3.0,33.0,14.0,14.0,13.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,86.0,BADM,312,3.519767
490,BADM 352,17.0,53.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0,BADM,352,3.928947
476,BADM 324,22.0,28.0,14.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,BADM,324,3.843056
512,BADM 453,35.0,23.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65.0,BADM,453,3.961538
492,BADM 356,17.0,19.0,9.0,5.0,6.0,3.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,64.0,BADM,356,3.601562
504,BADM 381,1.0,45.0,8.0,5.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0,BADM,381,3.831746
499,BADM 374,6.0,23.0,13.0,5.0,6.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,61.0,BADM,374,3.509836
479,BADM 329,4.0,36.0,12.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,BADM,329,3.846667
508,BADM 403,19.0,33.0,5.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,BADM,403,3.935000
491,BADM 353,4.0,48.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.0,BADM,353,3.981132
471,BADM 313,19.0,24.0,4.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.0,BADM,313,3.864151
480,BADM 330,11.0,21.0,12.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,BADM,330,3.844000
477,BADM 325,36.0,10.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0,BADM,325,3.959184
482,BADM 335,0.0,15.0,10.0,8.0,3.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,40.0,BADM,335,3.535000
474,BADM 322,5.0,11.0,8.0,7.0,4.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0,BADM,322,3.546154
497,BADM 370,0.0,33.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,BADM,370,3.939474
505,BADM 382,30.0,5.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,BADM,382,3.965789
478,BADM 326,1.0,16.0,8.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,BADM,326,3.675676
502,BADM 379,5.0,18.0,4.0,6.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,BADM,379,3.729730
501,BADM 378,26.0,8.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,BADM,378,3.956757
487,BADM 346,4.0,16.0,10.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,BADM,346,3.829412
484,BADM 338,14.0,12.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,BADM,338,3.900000
506,BADM 383,0.0,26.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,BADM,383,3.939286
486,BADM 341,2.0,19.0,4.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,BADM,341,3.860714
507,BADM 395,18.0,4.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,28.0,BADM,395,3.728571
509,BADM 420,1.0,14.0,7.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,BADM,420,3.722222
500,BADM 375,6.0,12.0,5.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,BADM,375,3.818519
503,BADM 380,11.0,9.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,BADM,380,3.954545
481,BADM 331,3.0,13.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,21.0,BADM,331,3.833333
510,BADM 446,3.0,9.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,BADM,446,3.852381
475,BADM 323,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,323,NaN
498,BADM 371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,371,NaN
496,BADM 366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,366,NaN
495,BADM 362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,362,NaN
494,BADM 359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,359,NaN
493,BADM 358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,358,NaN
483,BADM 337,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,337,NaN
513,BADM 461,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,461,NaN
514,BADM 463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BADM,463,NaN

In [10]:
df_grouped[(df_grouped['Course Subject'] == 'FIN') & (df_grouped['Course Number'] < 500)].sort_values('Students', ascending=False)

,Course,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,Students,Course Subject,Course Number,Average Grade
1255,FIN 221,89.0,652.0,149.0,66.0,48.0,26.0,18.0,11.0,4.0,3.0,2.0,0.0,1.0,1069.0,FIN,221,3.763704
1256,FIN 230,114.0,133.0,39.0,8.0,4.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,1.0,309.0,FIN,230,3.868285
1258,FIN 300,20.0,37.0,46.0,38.0,32.0,15.0,12.0,16.0,4.0,5.0,4.0,1.0,1.0,231.0,FIN,300,3.193506
1267,FIN 411,56.0,60.0,21.0,11.0,8.0,7.0,2.0,1.0,1.0,1.0,0.0,0.0,2.0,170.0,FIN,411,3.708824
1278,FIN 435,0.0,133.0,25.0,3.0,6.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,169.0,FIN,435,3.870414
1259,FIN 321,20.0,40.0,17.0,23.0,20.0,8.0,4.0,4.0,0.0,2.0,1.0,0.0,2.0,141.0,FIN,321,3.412766
1261,FIN 390,0.0,95.0,27.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128.0,FIN,390,3.899219
1273,FIN 423,69.0,39.0,7.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.0,FIN,423,3.959322
1257,FIN 241,2.0,97.0,3.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,107.0,FIN,241,3.947664
1271,FIN 418,20.0,25.0,17.0,4.0,7.0,3.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,81.0,FIN,418,3.635802
1280,FIN 445,3.0,48.0,8.0,3.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,FIN,445,3.792857
1283,FIN 464,13.0,28.0,9.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,FIN,464,3.861404
1279,FIN 443,4.0,28.0,5.0,6.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0,FIN,443,3.755102
1274,FIN 424,0.0,14.0,4.0,14.0,7.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,FIN,424,3.451163
1260,FIN 380,27.0,11.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,42.0,FIN,380,3.859524
1265,FIN 394,0.0,33.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0,FIN,394,3.916667
1266,FIN 395,18.0,8.0,4.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,35.0,FIN,395,3.774286
1276,FIN 432,10.0,10.0,7.0,2.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,FIN,432,3.720588
1270,FIN 416,0.0,8.0,15.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,FIN,416,3.653125
1281,FIN 461,0.0,9.0,3.0,5.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,FIN,461,3.455556
1263,FIN 392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,392,NaN
1264,FIN 393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,393,NaN
1268,FIN 412,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,412,NaN
1262,FIN 391,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,391,NaN
1269,FIN 415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,415,NaN
1272,FIN 419,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,419,NaN
1275,FIN 425,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,425,NaN
1277,FIN 434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,434,NaN
1282,FIN 463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,463,NaN
1284,FIN 490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FIN,490,NaN